-
  name: pb for variable concept
  hosts: all
  vars:
    a: 10
    b: 20
    c: "WELL COME TO INDIA"
  tasks:
    - name: code to create a directory
      file:
        path: /opt/var-concept
        state: directory

    - name: code to create file data.txt
      file:
      path: /opt/var-concept/data.txt
      state: touch

    - name: code to write variable into file
      lineinfile:
        path: /opt/var-concept/data.txt
        state: present
        line: "The value of a is{{a}} \n The value of b is {{b}} \n The value of c is {{c}}"

