-
  name: pb on use case of loop
  hosts: client1
  tasks:
    - name: below code for yum installation using loop
      yum:
        name: "{{ item }}"
        state: present
      with_item:
        - git
        - docker
        - net-tools
        - finger