-
  name: pb on command module
  hosts: client1
  tasks:
    - name: code to install git app
      yum:
        name: git
        state: present

    - name: code to configure user.name in git
      command:
        cmd: git config --global user.name narendramodi

    - name: code to configure user.email in git
      command:
        cmd: git config --global user.email n.modi@gmail.com

    - name: code to create folder on client name
      command:
        cmd: mkdir India
