-
  name: pb on loop variable
  hosts: clinet1
  var:
    a: 10
    b: 20.50
    c: "ap05dc0505"
    d: "well come"
  tasks:
    - name: code to create a file
      file:
        path: /opt/variable.txt
        state: touch
      
    - name: code to write a message into file
      lineinfile:
        path: /opt/variable.txt
        state: present
        line: "The value of a is {{a}} and b is {{b}} and c is {{c}} and d is {{d}}"
